return {
  require "user.custom-plugins.cowsay.cows.default",
  require "user.custom-plugins.cowsay.cows.flaming-sheep",
  require "user.custom-plugins.cowsay.cows.tux",
  require "user.custom-plugins.cowsay.cows.luke-koala",
  require "user.custom-plugins.cowsay.cows.bud-frogs",
  require "user.custom-plugins.cowsay.cows.vader",
  -- require "user.custom-plugins.cowsay.cows.stegosaurus",
  require "user.custom-plugins.cowsay.cows.koala",
  -- require "user.custom-plugins.cowsay.cows.sage",
  require "user.custom-plugins.cowsay.cows.scowleton",
  require "user.custom-plugins.cowsay.cows.small",
  -- require "user.custom-plugins.cowsay.cows.squirrel",
  -- require "user.custom-plugins.cowsay.cows.elephant",
  require "user.custom-plugins.cowsay.cows.moose",
  require "user.custom-plugins.cowsay.cows.sheep",
  require "user.custom-plugins.cowsay.cows.cower",
  require "user.custom-plugins.cowsay.cows.satanic",
  require "user.custom-plugins.cowsay.cows.docker",
  require "user.custom-plugins.cowsay.cows.super-milker",
  require "user.custom-plugins.cowsay.cows.moofasa",
  -- require "user.custom-plugins.cowsay.cows.bong",
  require "user.custom-plugins.cowsay.cows.mutilated",
}
