return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "javascript",
      "tsx",
      "json",
      "jsonc",
      "lua",
      "php",
      "phpdoc",
      "python",
      "typescript",
      "css",
      "rust",
      "java",
      "yaml",
      "go",
      "html",
      "comment",
      "make",
      "dockerfile",
      "toml",
      "markdown",
      "markdown_inline",
      "svelte",
    },
  },
}
